on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: client
jobs:
  client-build:
    name: client-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          working-directory: client

      - name: Install dependencies
        run: npm install
        working-directory: client

      - run: npm run build
        working-directory: client

      - run: npm run format-check
        working-directory: client

      - run: npm test
        working-directory: client