on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: client
jobs:
  client-build:
    name: Client build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies and build project
        working-directory: client
        run: |
          npm install
          npm run build
          npm run lint
          npm run test:unit