name: "CI for builds"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: oktomx/screen-app

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login --username "${DOCKER_USERNAME}" --password-stdin <<< "${DOCKER_TOKEN}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build base
        run: |
          BUILD_IMAGE=${DOCKER_IMAGE} .docker/build.sh ${DOCKER_TAG}
          docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
        env:
          DOCKER_TAG: base

  build:
    runs-on: ubuntu-latest
    needs: [ build-base ]
    strategy:
      matrix:
        tags: [ firefox ]
    env:
      DOCKER_TAG: ${{ matrix.tags }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login --username "${DOCKER_USERNAME}" --password-stdin <<< "${DOCKER_TOKEN}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build container
        run: |
          BUILD_IMAGE=${DOCKER_IMAGE} .docker/build.sh ${DOCKER_TAG}
          docker push ${DOCKER_IMAGE}:${DOCKER_TAG}

      - name: Push latest tag
        run: |
          docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
          docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd screen-app && docker pull oktomx/screen-app:firefox &&  docker-compose restart
