name: CI Tests

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  client-build-test:
    name: Client build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies and build project
        working-directory: client
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test:unit

  server-build-test:
    name: Server build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: server

      - name: Install dependencies
        run: go mod tidy
        working-directory: server

      - name: Build server
        run: go build
        working-directory: server

      - name: Unit tests
        run: go test -v
        working-directory: server
