name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server-build-test:
    name: Server build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy
        working-directory: server

      - name: Build server
        run: go build
        working-directory: server

      - name: Unit tests
        run: go test -v
        working-directory: server
