on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: server
jobs:
  check-style:
    name: check-style
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: server

  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod tidy
        working-directory: server

      - name: Unit tests
        run: go test -v
        working-directory: server
